import LegalPage from '../components/LegalPage.jsx'

function Terms() {
  return (
    <LegalPage title="Terms of Service" updated="July 14, 2026">
      <section>
        <p>
          These terms cover your use of lumi, a free and open-source browser extension and
          optional local proxy server. By installing or using lumi, you agree to them. If
          you don&rsquo;t agree, don&rsquo;t use the software.
        </p>
      </section>

      <section>
        <h2>1. The software and its license</h2>
        <p>
          lumi is distributed under the{' '}
          <a href="https://github.com/Yi-99/lumi/blob/main/LICENSE" target="_blank" rel="noreferrer">
            MIT License
          </a>
          . You may use, copy, modify, and redistribute it under that license&rsquo;s terms.
          Where these terms and the MIT License overlap, the license governs your rights to
          the code itself.
        </p>
      </section>

      <section>
        <h2>2. Bring your own keys</h2>
        <p>
          lumi requires API keys that you obtain yourself from Anthropic, OpenAI, or Google.
          You are responsible for:
        </p>
        <ul>
          <li>All charges those providers bill to your keys.</li>
          <li>Keeping your keys secure and rotating them if you suspect exposure.</li>
          <li>
            Complying with each provider&rsquo;s terms of service and usage policies when
            you send text through lumi.
          </li>
        </ul>
      </section>

      <section>
        <h2>3. Acceptable use</h2>
        <p>
          Use lumi only in ways that are lawful and consistent with the policies of the AI
          providers you connect it to. Don&rsquo;t use it to process content you have no
          right to share with those providers.
        </p>
      </section>

      <section>
        <h2>4. The local proxy server</h2>
        <p>
          The optional proxy server is development-grade software intended to run on{' '}
          <code>localhost</code>. It ships without authentication. If you expose it beyond
          your own machine, you do so at your own risk and are responsible for securing it.
        </p>
      </section>

      <section>
        <h2>5. AI-generated content</h2>
        <p>
          Answers shown in the lookup card are generated by third-party AI models. They can
          be wrong, incomplete, or misleading, and they are not professional advice of any
          kind — medical, legal, financial, or otherwise. Verify anything that matters
          before relying on it.
        </p>
      </section>

      <section>
        <h2>6. No warranty</h2>
        <p>
          lumi is provided <em>&ldquo;as is&rdquo;</em>, without warranty of any kind,
          express or implied, including merchantability, fitness for a particular purpose,
          and non-infringement — as stated in the MIT License.
        </p>
      </section>

      <section>
        <h2>7. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, the authors and contributors of lumi are
          not liable for any claim, damages, or other liability arising from your use of the
          software — including provider charges, data loss, or decisions made based on
          AI-generated answers.
        </p>
      </section>

      <section>
        <h2>8. Changes</h2>
        <p>
          If these terms change, the update will appear on this page with a new date.
          Continued use of lumi after a change means you accept the updated terms.
        </p>
      </section>

      <section>
        <h2>9. Contact</h2>
        <p>
          Questions about these terms? Open an issue on{' '}
          <a href="https://github.com/Yi-99/lumi/issues" target="_blank" rel="noreferrer">
            GitHub
          </a>
          .
        </p>
      </section>
    </LegalPage>
  )
}

export default Terms
